### Index Method
GET http://localhost:3000/products.json

### Show Method
GET http://localhost:3000/products/2.json

### Create Method
POST http://localhost:3000/products.json
Content-Type: application/json

{
  "name": "Even Better Hiking Poles",
  "price": "23",
  "image_url": "test.com/image.png",
  "description": "This is a new type of tent."
}

### Update Method
PATCH http://localhost:3000/products/5.json
Content-Type: application/json

{
  "name": "Even Better Hiking Poles",
  "price": 200,
  "image_url": "test.com/image_trekking.json",
  "description": "These poles are even better than the KUIU poles!"
}

### Destroy Method
DELETE http://localhost:3000/products/16.json
