@jwt = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjozLCJleHAiOjE2NjI4MzYxMDV9.TSn1Lt5HDZ3PIO4N8FWcWEWhxistTJOzApI_GlmLh3I

### Index Method Product
GET http://localhost:3000/products.json
Authentication: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2NjI3NDA5NjZ9.OWY22aQwxgGbjT_SbtIcPf440pjemfa5HQJqrp1z4OE

### Show Method Product
GET http://localhost:3000/products/1.json

### Create Method Product
POST http://localhost:3000/products.json
Content-Type: application/json
Authorization: Bearer {{jwt}}

{
  "name": "Even Better Hiking Poles",
  "price": "23",
  "description": "This is a new type of tent.",
  "supplier_id": 1
}

### Update Method Product
PATCH http://localhost:3000/products/5.json
Content-Type: application/json
Authorization: Bearer {{jwt}}

{
  "name": "Even Better Hiking Poles",
  "price": 200,
  "description": "These poles are even better than the KUIU poles!",
  "supplier": "Even Better"
}

### Destroy Method Product
DELETE http://localhost:3000/products/5.json
Authorization: Bearer {{jwt}}

### Users create (signup)
POST http://localhost:3000/users.json
Content-Type: application/json

{
  "name": "admin",
  "email": "admin@test.com",
  "password": "password",
  "password_confirmation": "password"
}







### Index Method Supplier
GET http://localhost:3000/suppliers.json

### Show Method Supplier
GET http://localhost:3000/suppliers/2.json

### Create Method Supplier
POST http://localhost:3000/suppliers.json
Content-Type: application/json

{
  "name": "Nike",
  "email": "nike@gmail.com",
  "phone_number": "313-134-5132",
}

### Update Method Supplier
PATCH http://localhost:3000/suppliers/4.json
Content-Type: application/json

{
  "name": "Nike",
  "email": "nike@gmail.com",
  "phone_number": "313-134-5132",
}

### Destroy Method Supplier
DELETE http://localhost:3000/suppliers/5.json

### Sessions create (login)
POST http://localhost:3000/sessions.json
Content-Type: application/json

{
  "email": "admin@test.com",
  "password": "password",
  "admin": true
}

### Order index
GET http://localhost:3000/orders.json
Authorization: Bearer {{jwt}}

### Order show
GET http://localhost:3000/orders.json
Authorization: Bearer {{jwt}}

### Order create
POST http://localhost:3000/orders.json
Content-Type: application/json
Authorization: Bearer {{jwt}}

{
  "product_id": 2,
  "quantity": 1
}




